# Generated by Django 4.1.4 on 2023-01-08 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 1, 8, 17, 56, 57, 109713, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=300)),
                ('due_date', models.DateField(default=datetime.datetime(2023, 4, 8, 17, 56, 57, 109984, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateField(default=datetime.datetime(2023, 1, 8, 17, 56, 57, 110023, tzinfo=datetime.timezone.utc))),
                ('urgency', models.CharField(choices=[('URGENT', 'Urgent'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], default='BACKLOG', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 1, 8, 17, 56, 57, 110559, tzinfo=datetime.timezone.utc))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime(2023, 1, 8, 17, 56, 57, 110807, tzinfo=datetime.timezone.utc))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assignedUsers',
            field=models.ManyToManyField(related_name='tasksOfUser', through='core.TaskAssignedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='taksOfUser', through='core.TaskComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.task'),
        ),
    ]
