# Generated by Django 4.1.4 on 2022-12-14 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=300)),
                ('created_at', models.DateField(default=datetime.date(2022, 12, 14))),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 14)),
        ),
    ]
