# Generated by Django 4.1.4 on 2022-12-18 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 13, 51, 10, 863771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 13, 51, 10, 864114, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 13, 51, 10, 864077, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskcommentsmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 13, 51, 10, 864593, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TaskUserAssignedMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime(2022, 12, 18, 13, 51, 10, 864863, tzinfo=datetime.timezone.utc))),
                ('assignedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('onTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assignedUsers',
            field=models.ManyToManyField(related_name='assignedUsers', through='core.TaskUserAssignedMapping', to=settings.AUTH_USER_MODEL),
        ),
    ]
