# Generated by Django 4.1.4 on 2022-12-26 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_board_created_at_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='taskcommentsmapping',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='taskcommentsmapping',
            old_name='author',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 4, 58, 519821, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 4, 58, 520152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 17, 4, 58, 520117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskcommentsmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 4, 58, 520669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskuserassignedmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 4, 58, 520916, tzinfo=datetime.timezone.utc)),
        ),
    ]
