# Generated by Django 4.1.4 on 2022-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BL', 'Backlog'), ('TD', 'To Do')], default='BL', max_length=20),
        ),
    ]
