# Generated by Django 4.1.4 on 2022-12-26 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_task_id_taskcommentsmapping_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcommentsmapping',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 10, 33, 216297, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 10, 33, 216646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 17, 10, 33, 216576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskcommentsmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 10, 33, 217140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskuserassignedmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 10, 33, 217388, tzinfo=datetime.timezone.utc)),
        ),
    ]
