# Generated by Django 4.1.4 on 2023-04-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230208_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 4, 22, 10, 25, 28, 760334, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 10, 25, 28, 758850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 10, 25, 28, 759189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 10, 25, 28, 759153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskassigneduser',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 10, 25, 28, 760032, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 10, 25, 28, 759689, tzinfo=datetime.timezone.utc)),
        ),
    ]
