# Generated by Django 4.1.4 on 2022-12-18 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_board_created_at_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 11, 17, 34, 158345, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 11, 17, 34, 158701, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 11, 17, 34, 158663, tzinfo=datetime.timezone.utc)),
        ),
    ]
