# Generated by Django 4.1.4 on 2022-12-26 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_taskcommentsmapping_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 37, 15, 972579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 37, 15, 972973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 17, 37, 15, 972937, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskcommentsmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 37, 15, 973451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='taskuserassignedmapping',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 17, 37, 15, 973691, tzinfo=datetime.timezone.utc)),
        ),
    ]
