# Generated by Django 4.1.4 on 2022-12-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_task_subtask_task_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 16, 8, 3, 92689)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 17, 16, 8, 3, 92976)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 16, 8, 3, 92943)),
        ),
    ]
